services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_TEST_MODE: ${VITE_TEST_MODE}
    ports:
      - "8080:8080"
    env_file:
      - .env